// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD771gFYkES9lBuAHumtLwwP8jB8cfVTps',
    appId: '1:178532700072:android:13fd97d3ec406574afd79d',
    messagingSenderId: '178532700072',
    projectId: 'k-ecommerce-1fb9f',
    storageBucket: 'k-ecommerce-1fb9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVwiAc4I0_vbUigolUSYbwIkhfca321Qk',
    appId: '1:178532700072:ios:e1e4e9dcee6d8ddcafd79d',
    messagingSenderId: '178532700072',
    projectId: 'k-ecommerce-1fb9f',
    storageBucket: 'k-ecommerce-1fb9f.firebasestorage.app',
    androidClientId: '178532700072-d7ioq9kgbh0oovtm1ebudeedv0tit5sb.apps.googleusercontent.com',
    iosClientId: '178532700072-2bb2jk4d11e5qflnjkan8stsjikf95mg.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.tostignappUser',
  );
}
